Fixed the following bugs highlighted from Crashlytics:
Fatal Exception: android.content.ActivityNotFoundException
Unable to find explicit activity class {org.tyndalebt.storyproduceradv/org.tyndalebt.storyproduceradv.activities.MainBaseActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared <intent-filter>?

  In MainBaseActivity, when it attempts to go to the DownloadActivity and there
  is no internet connection, it gives a warning dialog and then is supposed to
  go back to MainActivity, but in a previous transaction I mistakenly switched
  it to go to MainBaseActivity (wrong) instead of MainActivity (correct).

Fatal Exception: java.lang.IllegalStateException
The content of the adapter has changed but ListView did not receive a notification. Make sure the content of your adapter is not modified from a background thread, but only from the UI thread. Make sure your adapter calls notifyDataSetChanged() when its content changes. [in ListView(2131296815, class android.widget.ListView) with Adapter(class org.tyndalebt.storyproduceradv.controller.storylist.ListAdapter)]

  Needed to add a call to adapter.notifyDataSetChanged() in updateStoryListDisplay()
  when the story list gets updated from delete or restore operation from the
  Translation Data Backup screen.  The update actually occurred, but the crash
  was recorded in Crashlytics.

java.lang.IllegalArgumentException: Failed to determine if 9C33-6BBD:SPFIles/videos/000_RayTestXXXxxzz_PxMvTx.mp4 is child of 9C33-6BBD:SPFIles: java.io.FileNotFoundException: Missing file for 9C33-6BBD:SPFIles/videos/000_RayTestXXXxxzz_PxMvTx.mp4 at /storage/9C33-6BBD/SPFIles/videos/000_RayTestXXXxxzz_PxMvTx.mp4
   I had modified the contents of FileIO.copyToWorkspacePath to call copyFile
   as an optimization.  This was incorrect because the 2nd parameter to copyFile
   was a directory URI but in this case it was the filename URI that was being
   passed to copyFile.  And in the case of video creation, we cannot use copyFile
   because the original video name was tempVideo and needed to be modified to
   its specific name.